# Generated by Django 4.0.6 on 2022-08-04 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklabels',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
